
# APPLICATION CONFIGURATION
#application Name
spring.application.name=dynamic-config-manager

# SERVER CONFIGURATION
#default = 8080
server.port=8080

# DATABASE CONFIGURATION(H2)
#stored in memory
spring.datasource.url=jdbc:h2:mem:configdb

#driver class
spring.datasource.driverClassName=org.h2.Driver

#credentls
spring.datasource.username=sa
spring.datasource.password=

# JPA/HIBERNATE CONFIGURATION
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
#create tables on startup drop on shutdown
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# H2 CONSOLE CONFIGURATION
#database view in browser
spring.h2.console.enabled=true

# URL path
spring.h2.console.path=/h2-console


# JSON CONFIGURATION
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.indent-output=true


# LOGGING CONFIGURATION
logging.level.com.example.configmanager=DEBUG

# spring web log level
logging.level.org.springframework.web=INFO

#Hibernate SQL
logging.level.org.hibernate.SQL=DEBUG